spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/department_db
    username: postgres
    password: changeme
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
   endpoints:
     web:
       exposure:
         include: "*"
server:
  port: 8082
app:
  welcome: hi
